//All action types are mentioned here as constants
export const SIGN_IN = "SIGN_IN";
export const ADD_USER = "ADD_USER";
export const SIGN_IN_ERROR = "SIGN_IN_ERROR";
export const ADD_USER_ERROR = "ADD_USER_ERROR";

export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";

export const LOAD_SCREEN = "LOAD_SCREEN";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_ERROR = "CHANGE_PASSWORD_ERROR";

// type for LIBRARY ACTIONS
export const UPLOAD_FILES = "UPLOAD_LIBRARY_FILES";
export const UPLOAD_FILES_ERROR = "UPLOAD_LIBRARY_FILES_ERROR";
export const GET_ALL_LIBRARY_FILES = "GET_ALL_LIBRARY_FILES";
export const GET_ALL_LIBRARY_FILES_ERROR = "GET_ALL_LIBRARY_FILES_ERROR";
export const CLEAR_LIBRARY_ERROR = "CLEAR_LIBRARY_ERROR";
export const DELETE_GALLERY_IMAGE = "DELETE_GALLERY_IMAGE";
export const DELETE_GALLERY_IMAGE_ERROR = "DELETE_GALLERY_IMAGE_ERROR";
export const VERIFY_UNIQUE_CODE = "VERIFY_UNIQUE_CODE";
export const VERIFY_UNIQUE_CODE_ERROR = "VERIFY_UNIQUE_CODE_ERROR";
